### ISSUE TITLE
model field with unique=True causes an exception

### ISSUE THREAD

**Issue by dfrankow** [claytondaley/drf-writable-nested#1]
Run the unit tests of https://github.com/dfrankow/drf-writable-example/commit/2832ce8df6427cb6b94682d12243bccb39047b2e

I think the problem is `unique=True` on User.username.

I attach the error.

[error.txt](https://github.com/claytondaley/drf-writable-nested/files/3114558/error.txt)

**Comment by claytondaley** [comment]
OK I had a really weird issue... a loop used the variable `name`, but the loop had the string "name" hard coded which must have (coincidentally) been the unique in my internal usage.  Fixed in master.  Looking into your second test case.

**Comment by claytondaley** [comment]
The second test still fails, but due to an erroneous assertion.  You're using `GetOrCreate` on the `AccessSerializer`.  Both are requesting the same `key` so both get it.  I assume you really want a `CreateOnlyNestedSerializer` for that case.

**Comment by claytondaley** [comment]
I went ahead and added a `CreateOnlyNestedSerializerMixin` in master.  I dropped it into your example and get a different (but expected) error because the two requests use the same `key`.  This causes a unique key collision.

**Comment by claytondaley** [comment]
... just to make sure the code was working, when I also drop the `unique` constraint on `AccessKey.key`, the test passes.

**Comment by dfrankow** [comment]
Yep, I think this one is fixed.
