### ISSUE TITLE
Race condition in GetOrCreateNestedSerializerMixin ?

### ISSUE THREAD

**Issue by dfrankow** [claytondaley/drf-writable-nested#3]
I have the following code:

```
class ExampleSerializer(serializers.ModelSerializer,
                              GetOrCreateNestedSerializerMixin):
    # match on this unique id
    DEFAULT_MATCH_ON = ['one', 'two']

    class Meta:
        model = Example
        fields = ('one', 'two')
```

and when I create two objects that have this Example nested in them with the same value, I get the stack trace attached, with the error:

`MultipleObjectsReturned at /api/v0/an_object/1/ - get() returned more than one Example -- it returned 2!`

It would take awhile for me to make a test case to do this, so I'm filing without it for now.

I can make the race condition go away by random sleeps. Clearly that's a hack.

I suspect there is a check for DEFAULT_MATCH_ON fields, and then an action based on whether the row exists, but those two aren't wrapped in a transaction.  That would be a race condition for two simultaneous submissions of something that would match.

[drf_stack.txt](https://github.com/claytondaley/drf-writable-nested/files/3536227/drf_stack.txt)

**Comment by claytondaley** [comment]
I think you *must* add a `unique_together` on the two fields.  Technically speaking, I think it would be valid to commit both rows in a concurrent transaction.  Specifically,

 - Transaction 1 starts
 - Transaction 2 starts
 - Transaction 1 and 2 check for existence
 - Transaction 1 creates
 - Transaction 2 is blocked trying to create
 - Transaction 1 commits
 - Transaction 2 is unblocked and commits (no uniqueness violation)
 - Transaction 2 commits

Once the two are inside a transaction, there's no way for the one to see the other.  You need one of the requests to fail and be retried (to actually find the field created by the other).

**Comment by claytondaley** [comment]
This is sorta like the comment about `UniqueFieldsMixin` in the base package.  We assume (but do not check) that the underlying fields are unique.  If they are not, behavior is undefined.

**Comment by dfrankow** [comment]
Yes, I put a unique_together constraint in the model after I saw this. Then one request failed the uniqueness constraint.

But it seems to me it wouldn't have to. One request could be blocked checking for an existing record while the other created it. Then when the first succeeded, the second would find the row and not create it.

**Comment by claytondaley** [comment]
OK here's the rub.  Postgres has a way to lock an existing row from a subsequent select (and Django exposes it using `select_for_update`).  Unfortunately, there's no way to lock a to-be-created row.  Even Django's `get_or_create` seems to use the same pattern:

```
        try:
            return self.get(**lookup), False
        except self.model.DoesNotExist:
            return self._create_object_from_params(lookup, params)
```

It looks like the only way to guarantee the behavior you desire is to lock the entire table.  I hesitate to do something that extreme in a class that may be grabbed without understanding the consequences.  I hope I'm wrong, but spent some time searching and don't see an obvious alternative.

**Comment by dfrankow** [comment]
https://stackoverflow.com/a/2235624/34935 ?

http://python.6.x6.nabble.com/How-to-atomically-create-and-lock-an-object-td5190555.html
?

**Comment by claytondaley** [comment]
Perfect.  I guess I didn't get deep enough into the `get_or_create` code.  I changed the package to `get_or_create` locally before looking at it to see if it helped.  I'll add `select_for_update` as well since the get or create serializer is willing to update fields in the related object and push it up shortly.

**Comment by claytondaley** [comment]
I pushed up a new version (with fixes for a different test/behavior as well).  Can you test that?

**Comment by claytondaley** [comment]
I'm going to close this issue.  Please reopen if the issue persists.  Note that you *must* include the uniqueness constraint or the behavior will not work correctly since the `get_or_create` sequence depends on the unique constraint.

**Comment by dfrankow** [comment]
I now get errors on unit tests that used to pass. I'll have to dig in further.

**Comment by claytondaley** [comment]
Odd. I actually fixed unit tests during the upgrade. Though I didn't run
all mixes of python and Django so maybe it's an issue there.

**Comment by dfrankow** [comment]
https://github.com/dfrankow/drf-writable-example/tree/get_or_create_clayton (using https://github.com/claytondaley/drf-writable-nested/zipball/b49aefae8a0bc7ce763e007ab3d474d11cfd4b07/ in requirements.txt) passes its tests.

If I replace that line in requirements.txt with https://github.com/claytondaley/drf-writable-nested/zipball/0f99c39e9000abbe4dc52648acaaafdc1643b9e4/ (your latest check-in), the tests fail:

```
======================================================================
FAIL: test_save_site_twice (hello.tests.SerializerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dan/work/appcensus/drf-writable-example/hello/tests.py", line 105, in test_save_site_twice
    self.assertEqual(1, Site.objects.filter(url=url).count())
AssertionError: 1 != 2

======================================================================
FAIL: test_save_twice (hello.tests.SerializerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dan/work/appcensus/drf-writable-example/hello/tests.py", line 86, in test_save_twice
    user2.profile.access_key.id)
AssertionError: 1 != 2
```

**Comment by claytondaley** [comment]
I pulled your latest (that I can see) and can't reproduce:

SHA-1: 5e007237fb381dfa96d779a7935aceb48b32259f
* fix tests

  Requirement already satisfied (use --upgrade to upgrade):
drf-writable-nested==0.5.1 from
https://github.com/claytondaley/drf-writable-nested/zipball/0f99c39e9000abbe4dc52648acaaafdc1643b9e4/
in c:\users\clayto~2\envs\drf-wr~2\lib\site-packages (from -r
requirements.txt (line 4))

![tests pass](https://user-images.githubusercontent.com/1097439/63655023-2a22b080-c748-11e9-8421-600e3f2d4da8.png)

Here are all of my dependencies:

![all dependencies in virtual environment](https://user-images.githubusercontent.com/1097439/63655033-41619e00-c748-11e9-9c8d-41ea365337af.png)

**Comment by dfrankow** [comment]
I have to uninstall drf-writable-nested, then reinstall, to get it to install the correct version.

pip downloads the right version, but then doesn't apply it because the version number (0.5.1) hasn't changed in your source.

I can still repro the error: tests work with your b49aefae8a0bc7ce763e007ab3d474d11cfd4b07, but don't with your 0f99c39e9000abbe4dc52648acaaafdc1643b9e4.

**Comment by dfrankow** [comment]
And I am using the SHA you mentioned (5e007237fb381dfa96d779a7935aceb48b32259f).

**Comment by claytondaley** [comment]
You were right about uninstalling first.  I'm looking into it now.

**Comment by claytondaley** [comment]
Try the latest.  I think I may have been corrupting the _validated_data
dict somehow.  I changed the way I was using _validated_data and -- while I
was at it -- merged in 0.5.2 from upstream and restructured some code to
eliminate duplication.  FWIW I really need to move some of your test cases
into my repo so I automatically verify them every time, but you'd need to
add a compatible license (or contribute by PR).

**Comment by dfrankow** [comment]
I added an Apache license (both on master and the get_or_create_clayton
branch), which should let you do whatever you want.

Here is the latest on that branch:
https://github.com/dfrankow/drf-writable-example/commit/6672d15ae7b529dad31d3e66fd130f4616585b89

I would add the PR, but I haven't looked carefully at your tests.

**Comment by claytondaley** [comment]
Thanks but I'm reasonably confident I can't use Apache code in a BSD library (like this one) because BSD wouldn't continue to enforce the patent restrictions in Apache.  My opinion seems to be echoed [here](https://softwareengineering.stackexchange.com/a/40571/150177):

> Do you have the right to take Apache licensed code and re-license it as BSD? I highly doubt it. I believe Apache has a couple more restrictions on it than BSD. 

Worst case scenario, I can write tests with comparable behavior.

**Comment by dfrankow** [comment]
Switched to 2-clause BSD.

**Comment by claytondaley** [comment]
Thanks!  Can you confirm that tests are passing on your end too? 

I really appreciate your use of the package.  We've had some duplicates show up in our system and it was rare so virtually impossible to troubleshoot.  I assumed our issue was the absence of a uniqueness constraint -- which isn't easy in our data model -- but we would have run into this same issue even if we had resolved the uniqueness constraint.

**Comment by dfrankow** [comment]
All the tests I have now pass with latest
(188691e59596b4435e7fc05fc55444ccd60e1226)!

1. The drf-writable-example tests.
2. The tests we have in our system that were showing weirdness.

Thank you!

**Comment by dfrankow** [comment]
Ah curses. I tried this on our real system and gave the exception below. Now I've got to scramble because I put it in prod. Perhaps I didn't rebuild an image somewhere when I was testing?

I'm on django 2.2.3 and drf-writable-nested clayton's 188691e59596b4435e7fc05fc55444ccd60e1226 (head).

```
TransactionManagementError at <our REST API URL> select_for_update cannot be used outside of a transaction

Traceback:

File “/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py” in inner

34.             response = get_response(request)
File “/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py” in _get_response
115.                 response = self.process_exception_by_middleware(e, request)
File “/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py” in _get_response
113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File “/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py” in wrapped_view
54.         return view_func(*args, **kwargs)
File “/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py” in view
116.             return self.dispatch(request, *args, **kwargs)
File “/usr/local/lib/python3.7/site-packages/rest_framework/views.py” in dispatch
495.             response = self.handle_exception(exc)
File “/usr/local/lib/python3.7/site-packages/rest_framework/views.py” in handle_exception
455.             self.raise_uncaught_exception(exc)
File “/usr/local/lib/python3.7/site-packages/rest_framework/views.py” in dispatch
492.             response = handler(request, *args, **kwargs)
File “/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py” in partial_update
84.         return self.update(request, *args, **kwargs)
File “/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py” in update
70.         self.perform_update(serializer)
File “/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py” in perform_update
80.         serializer.save()
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in save
232.         return super(BaseNestedModelSerializer, self).save(**kwargs)
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in save
455.         self._save_direct_relations(kwargs)
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in _save_direct_relations
517.             self._validated_data[field_name] = field.save(**kwargs.pop(field_name, {}))
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in save
232.         return super(BaseNestedModelSerializer, self).save(**kwargs)
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in save
455.         self._save_direct_relations(kwargs)
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in _save_direct_relations
517.             self._validated_data[field_name] = field.save(**kwargs.pop(field_name, {}))
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in save
455.         self._save_direct_relations(kwargs)
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in _save_direct_relations
517.             self._validated_data[field_name] = field.save(**kwargs.pop(field_name, {}))
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in save
456.         instance = super().save(**kwargs)
File “/usr/local/lib/python3.7/site-packages/drf_writable_nested/mixins.py” in save
687.             match, created = self.queryset.select_for_update().get_or_create(defaults=defaults, **match_on)
File “/usr/local/lib/python3.7/site-packages/django/db/models/query.py” in get_or_create
538.             return self.get(**kwargs), False
File “/usr/local/lib/python3.7/site-packages/django/db/models/query.py” in get
402.         num = len(clone)
File “/usr/local/lib/python3.7/site-packages/django/db/models/query.py” in _len_
256.         self._fetch_all()
File “/usr/local/lib/python3.7/site-packages/django/db/models/query.py” in _fetch_all
1242.             self._result_cache = list(self._iterable_class(self))
File “/usr/local/lib/python3.7/site-packages/django/db/models/query.py” in _iter_
55.         results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
File “/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py” in execute_sql
1087.             sql, params = self.as_sql()
File “/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py” in as_sql
518.                         raise TransactionManagementError('select_for_update cannot be used outside of a transaction.')
```

**Comment by claytondaley** [comment]
Django's testing framework uses transactions by default.  Wrap your views in `@transaction.atomic` as a quick fix.

**Comment by claytondaley** [comment]
I'll wrap the method in @transaction.atomic too as a guard.

**Comment by dfrankow** [comment]
Thanks, I'll look into that!

**Comment by claytondaley** [comment]
Update pushed.  You may be able to rebuild.

**Comment by dfrankow** [comment]
I believe this fix worked. I really appreciate it!

**Comment by claytondaley** [comment]
YW.  Very lucky that I read the "tests are run in transactions" bit while investigating `select_for_update` or I would have been very confused.  We also run all of our views in transactions to ensure the integrity of business logic so we wouldn't notice the limitation either.
